version: '2'

services:

  goc:
    image: shaonian/goc:v1.0
    network_mode: host
    ports:
      - "7777:7777"
    command:
      - ./goc
      - server

  
  app_1:
    image: shaonian/simple-go-server:v1.0
    restart: always
    network_mode: host
    ports:
      - "5000:5000"
    command:
      - ./simple-go-server
      - :5000
    depends_on:
      - goc
  
  app_2:
    image: shaonian/simple-go-server:v1.0
    restart: always
    network_mode: host
    ports:
      - "5001:5001"
    command:
      - ./simple-go-server
      - :5001
    depends_on:
      - goc